## Ciencia de datos con Python - Preparación para la certificación PCEP de Python Institute-Día 7a

In [2]:
import pandas as pd

# Leemos excel ficheros en su ruta
agosto2014 = pd.read_excel('/Users/andresrojo/Desktop/Python-PCEP/recursos_dia6/VentasGroucery_Meses.xlsx',
                        sheet_name= 'Ventas Agosto 2014')

septiembre2014 = pd.read_excel('/Users/andresrojo/Desktop/Python-PCEP/recursos_dia6/VentasGroucery_Meses.xlsx',
                        sheet_name= 'Ventas Septiembre 2014')

octubre2014 = pd.read_excel('/Users/andresrojo/Desktop/Python-PCEP/recursos_dia6/VentasGroucery_Meses.xlsx',
                        sheet_name= 'Ventas Octubre 2014')
octubre2014.head(5) # lo comprobamos
# unimos los dataframes en uno solo, deben coincidir en columnas, si no se crearán NAN
trimestre2014 = pd.concat([agosto2014, septiembre2014, octubre2014], ignore_index = True)
print(trimestre2014.head(5))
# formamos la columna Amount = Unit Price * Quantity

trimestre2014['Amount'] = trimestre2014['Unit Price'] * trimestre2014['Quantity']
trimestre2014

   Order ID                        Product        Category  Unit Price  \
0     10248  Singaporean Hokkien Fried Mee  Grains/Cereals         9.8
1     10248         Mozzarella di Giovanni  Dairy Products        34.8
2     10248                 Queso Cabrales  Dairy Products        14.0
3     10249                           Tofu         Produce        18.6
4     10249          Manjimup Dried Apples         Produce        42.4

   Quantity                   Customer Ship City Ship Country Order Date
0         1  Vins et alcools Chevalier     Reims       France 2014-08-04
1         5  Vins et alcools Chevalier     Reims       France 2014-08-04
2        12  Vins et alcools Chevalier     Reims       France 2014-08-04
3         9         Toms Spezialitäten   Münster      Germany 2014-08-05
4        40         Toms Spezialitäten   Münster      Germany 2014-08-05

,Order ID,Product,Category,Unit Price,Quantity,Customer,Ship City,Ship Country,Order Date,Amount
0,10248,Singaporean Hokkien Fried Mee,Grains/Cereals,9.8,1,Vins et alcools Chevalier,Reims,France,2014-08-04,9.8
1,10248,Mozzarella di Giovanni,Dairy Products,34.8,5,Vins et alcools Chevalier,Reims,France,2014-08-04,174.0
2,10248,Queso Cabrales,Dairy Products,14.0,12,Vins et alcools Chevalier,Reims,France,2014-08-04,168.0
3,10249,Tofu,Produce,18.6,9,Toms Spezialitäten,Münster,Germany,2014-08-05,167.4
4,10249,Manjimup Dried Apples,Produce,42.4,40,Toms Spezialitäten,Münster,Germany,2014-08-05,1696.0
...,...,...,...,...,...,...,...,...,...,...
180,10315,Sasquatch Ale,Beverages,11.2,14,Island Trading,Cowes,UK,2014-10-27,156.8
181,10315,Outback Lager,Beverages,12.0,30,Island Trading,Cowes,UK,2014-10-27,360.0
182,10316,Jack's New England Clam Chowder,Seafood,7.7,10,Rattlesnake Canyon Grocery,Albuquerque,USA,2014-10-28,77.0
183,10316,Tarte au sucre,Confections,39.4,70,Rattlesnake Canyon Grocery,Albuquerque,USA,2014-10-28,2758.0
184,10317,Chai,Beverages,14.4,20,Lonesome Pine Restaurant,Portland,USA,2014-10-31,288.0

In [1]:
# iloc[indice fila, indice columna]. 'iloc' es de escritura y de lectura
trimestre2014.iloc[1,1] # me devuelve el objeto contenido en la primera fila, en la primera columna
# Modificamos el interior del contenido en ese indice de la tabla
trimestre2014.iloc[1,1] = "Queso de Cabrales"
print(trimestre2014.iloc[1,1])# Visualizamos

NameError: name 'trimestre2014' is not defined

In [ ]:
# Con 'iloc[]', puedo poner todas las filas y algunas de las columnas en el orden que yo quiera
# trimestre2014.iloc[:,[5,3,6,1]] en este orden indicadas con su índice
trimestre2014.iloc[:,[5,3,6,1]] # muestra todas las filas de las columnas seleccionadas

,Customer,Unit Price,Ship City,Product
0,Vins et alcools Chevalier,9.8,Reims,Singaporean Hokkien Fried Mee
1,Vins et alcools Chevalier,34.8,Reims,Queso de Cabrales
2,Vins et alcools Chevalier,14.0,Reims,Queso Cabrales
3,Toms Spezialitäten,18.6,Münster,Tofu
4,Toms Spezialitäten,42.4,Münster,Manjimup Dried Apples
...,...,...,...,...
180,Island Trading,11.2,Cowes,Sasquatch Ale
181,Island Trading,12.0,Cowes,Outback Lager
182,Rattlesnake Canyon Grocery,7.7,Albuquerque,Jack's New England Clam Chowder
183,Rattlesnake Canyon Grocery,39.4,Albuquerque,Tarte au sucre
184,Lonesome Pine Restaurant,14.4,Portland,Chai

In [3]:
# Recorrer todo el DataFrames, para ello utilizaremos un bucle, el bucle 'for'. Necesito saber el número de iteraciones,
# que es igual al número de filas con len()

print(len(trimestre2014), 'filas') # con len() averiguamos el número de filas

# El número de columnas 
print(len(trimestre2014.columns), 'Columnas')

185 filas
10 Columnas

In [ ]:
# Vamos a recorrer el Dataframe e imprimir  el producto y entre paréntesis su categoria

filas = len(trimestre2014) # número total de filas

for i in range(0,filas): # no es una 'lista' por eso hhacemos el range, filas es un número
    print(trimestre2014.iloc[i,1] + "-("+trimestre2014.iloc[i,2]+")")

Singaporean Hokkien Fried Mee-(Grains/Cereals)
Queso de Cabrales-(Dairy Products)
Queso Cabrales-(Dairy Products)
Tofu-(Produce)
Manjimup Dried Apples-(Produce)
Louisiana Fiery Hot Pepper Sauce-(Condiments)
Jack's New England Clam Chowder-(Seafood)
Manjimup Dried Apples-(Produce)
Louisiana Fiery Hot Pepper Sauce-(Condiments)
Gustaf's Knäckebröd-(Grains/Cereals)
Ravioli Angelo-(Grains/Cereals)
Sir Rodney's Marmalade-(Confections)
Geitost-(Dairy Products)
Camembert Pierrot-(Dairy Products)
Maxilaku-(Confections)
Chartreuse verte-(Beverages)
Gorgonzola Telino-(Dairy Products)
Pâté chinois-(Meat/Poultry)
Longlife Tofu-(Produce)
Guaraná Fantástica-(Beverages)
Raclette Courdavault-(Dairy Products)
Chang-(Beverages)
Pavlova-(Confections)
Inlagd Sill-(Seafood)
Perth Pasties-(Meat/Poultry)
Original Frankfurter grüne Soße-(Condiments)
Schoggi Schokolade-(Confections)
Chartreuse verte-(Beverages)
Original Frankfurter grüne Soße-(Condiments)
Chang-(Beverages)
Chef Anton's Gumbo Mix-(Condiments)
Mascarpone Fabioli-(Dairy Products)
Sir Rodney's Scones-(Confections)
Gravad lax-(Seafood)
Jack's New England Clam Chowder-(Seafood)
Ravioli Angelo-(Grains/Cereals)
Tarte au sucre-(Confections)
Outback Lager-(Beverages)
Sir Rodney's Scones-(Confections)
Steeleye Stout-(Beverages)
Chef Anton's Gumbo Mix-(Condiments)
Uncle Bob's Organic Dried Pears-(Produce)
Gnocchi di nonna Alice-(Grains/Cereals)
Pavlova-(Confections)
Guaraná Fantástica-(Beverages)
Nord-Ost Matjeshering-(Seafood)
Longlife Tofu-(Produce)
Chang-(Beverages)
Jack's New England Clam Chowder-(Seafood)
Alice Mutton-(Meat/Poultry)
Outback Lager-(Beverages)
Queso Manchego La Pastora-(Dairy Products)
Boston Crab Meat-(Seafood)
Raclette Courdavault-(Dairy Products)
Lakkalikööri-(Beverages)
Thüringer Rostbratwurst-(Meat/Poultry)
Mozzarella di Giovanni-(Dairy Products)
Geitost-(Dairy Products)
Mozzarella di Giovanni-(Dairy Products)
Ipoh Coffee-(Beverages)
Inlagd Sill-(Seafood)
Geitost-(Dairy Products)
Sir Rodney's Marmalade-(Confections)
Gorgonzola Telino-(Dairy Products)
Mozzarella di Giovanni-(Dairy Products)
Boston Crab Meat-(Seafood)
Geitost-(Dairy Products)
Gorgonzola Telino-(Dairy Products)
Ikura-(Seafood)
Lakkalikööri-(Beverages)
Fløtemysost-(Dairy Products)
Mozzarella di Giovanni-(Dairy Products)
Guaraná Fantástica-(Beverages)
Raclette Courdavault-(Dairy Products)
Ikura-(Seafood)
Konbu-(Seafood)
Tarte au sucre-(Confections)
Rössle Sauerkraut-(Produce)
Gula Malacca-(Condiments)
Raclette Courdavault-(Dairy Products)
Vegie-spread-(Condiments)
Röd Kaviar-(Seafood)
Alice Mutton-(Meat/Poultry)
Guaraná Fantástica-(Beverages)
Pâté chinois-(Meat/Poultry)
Rhönbräu Klosterbier-(Beverages)
Teatime Chocolate Biscuits-(Confections)
Guaraná Fantástica-(Beverages)
Steeleye Stout-(Beverages)
Nord-Ost Matjeshering-(Seafood)
Ravioli Angelo-(Grains/Cereals)
Genen Shouyu-(Condiments)
Mozzarella di Giovanni-(Dairy Products)
Teatime Chocolate Biscuits-(Confections)
Camembert Pierrot-(Dairy Products)
Schoggi Schokolade-(Confections)
Gula Malacca-(Condiments)
Camembert Pierrot-(Dairy Products)
Laughing Lumberjack Lager-(Beverages)
Perth Pasties-(Meat/Poultry)
Boston Crab Meat-(Seafood)
Chai-(Beverages)
Tarte au sucre-(Confections)
Steeleye Stout-(Beverages)
Pavlova-(Confections)
Sasquatch Ale-(Beverages)
Spegesild-(Seafood)
Scottish Longbreads-(Confections)
Tourtière-(Meat/Poultry)
Aniseed Syrup-(Condiments)
Wimmers gute Semmelknödel-(Grains/Cereals)
Chef Anton's Gumbo Mix-(Condiments)
Thüringer Rostbratwurst-(Meat/Poultry)
Maxilaku-(Confections)
Original Frankfurter grüne Soße-(Condiments)
Manjimup Dried Apples-(Produce)
Konbu-(Seafood)
Gula Malacca-(Condiments)
Sir Rodney's Marmalade-(Confections)
Carnarvon Tigers-(Seafood)
Guaraná Fantástica-(Beverages)
Vegie-spread-(Condiments)
Rhönbräu Klosterbier-(Beverages)
Camembert Pierrot-(Dairy Products)
Rhönbräu Klosterbier-(Beverages)
Ipoh Coffee-(Beverages)
Alice Mutton-(Meat/Poultry)
Chai-(Beverages)
Gnocchi di nonna Alice-(Grains/Cereals)
Queso Cabrales-(Dairy Products)
Pavlova-(Confections)
Gudbrandsdalsost-(Dairy Products)
Chartreuse verte-(Beverages)
Mozzarella di Giovanni-(Dairy Products)
Chang-(Beverages)
Tarte au sucre-(Confections)
Raclette Courdavault-(Dairy Products)
Inlagd Sill-(Seafood)
Teatime Chocolate Biscuits-(Confections)
Outback Lager-(Beverages)
Louisiana Hot Spiced Okra-(Condiments)
Scottish Longbreads-(Confections)
Gnocchi di nonna Alice-(Grains/Cereals)
Boston Crab Meat-(Seafood)
Ipoh Coffee-(Beverages)
Alice Mutton-(Meat/Poultry)
Rössle Sauerkraut-(Produce)
Boston Crab Meat-(Seafood)
Louisiana Fiery Hot Pepper Sauce-(Condiments)
Scottish Longbreads-(Confections)
Fløtemysost-(Dairy Products)
Raclette Courdavault-(Dairy Products)
Maxilaku-(Confections)
Thüringer Rostbratwurst-(Meat/Poultry)
Chartreuse verte-(Beverages)
Carnarvon Tigers-(Seafood)
Nord-Ost Matjeshering-(Seafood)
Perth Pasties-(Meat/Poultry)
Tourtière-(Meat/Poultry)
Tarte au sucre-(Confections)
Scottish Longbreads-(Confections)
Outback Lager-(Beverages)
Gudbrandsdalsost-(Dairy Products)
Chef Anton's Cajun Seasoning-(Condiments)
Grandma's Boysenberry Spread-(Condiments)
Singaporean Hokkien Fried Mee-(Grains/Cereals)
Ipoh Coffee-(Beverages)
Fløtemysost-(Dairy Products)
Pavlova-(Confections)
Tarte au sucre-(Confections)
Singaporean Hokkien Fried Mee-(Grains/Cereals)
Gudbrandsdalsost-(Dairy Products)
Rössle Sauerkraut-(Produce)
Ipoh Coffee-(Beverages)
Perth Pasties-(Meat/Poultry)
Rhönbräu Klosterbier-(Beverages)
Inlagd Sill-(Seafood)
Tarte au sucre-(Confections)
Mascarpone Fabioli-(Dairy Products)
Escargots de Bourgogne-(Seafood)
Sasquatch Ale-(Beverages)
Outback Lager-(Beverages)
Jack's New England Clam Chowder-(Seafood)
Tarte au sucre-(Confections)
Chai-(Beverages)

## PRACTICA 33:
* Recorrer con un bucle (iloc) y for el dataframe trimestre2014 y cambiar el valor de la columna 'Category', para donde ponga 'Seafood' ponga _pescado_ y donde ponga 'Beverages' ponga _bebidas_.

In [6]:
# Ponemos la longitud en 'filas' del dataset 
filas = len(trimestre2014)

for i in range(0, filas):
    if trimestre2014.iloc[i,2] == 'Seafood':# el iloc solo admite integers
        trimestre2014.iloc[i,2] = 'Pescado'
    elif trimestre2014.iloc[i,trimestre2014.columns.get_loc('Category')] == 'Beverages': # de esta forma nos retorna el índice de la columna
        trimestre2014.iloc[i,trimestre2014.columns.get_loc('Category')] = 'Bebidas'
    
trimestre2014
# Nos da el indice en funcion del nombre de la columna
print(trimestre2014.columns.get_loc('Category'))
trimestre2014

2

,Order ID,Product,Category,Unit Price,Quantity,Customer,Ship City,Ship Country,Order Date,Amount
0,10248,Singaporean Hokkien Fried Mee,Grains/Cereals,9.8,1,Vins et alcools Chevalier,Reims,France,2014-08-04,9.8
1,10248,Mozzarella di Giovanni,Dairy Products,34.8,5,Vins et alcools Chevalier,Reims,France,2014-08-04,174.0
2,10248,Queso Cabrales,Dairy Products,14.0,12,Vins et alcools Chevalier,Reims,France,2014-08-04,168.0
3,10249,Tofu,Produce,18.6,9,Toms Spezialitäten,Münster,Germany,2014-08-05,167.4
4,10249,Manjimup Dried Apples,Produce,42.4,40,Toms Spezialitäten,Münster,Germany,2014-08-05,1696.0
...,...,...,...,...,...,...,...,...,...,...
180,10315,Sasquatch Ale,Bebidas,11.2,14,Island Trading,Cowes,UK,2014-10-27,156.8
181,10315,Outback Lager,Bebidas,12.0,30,Island Trading,Cowes,UK,2014-10-27,360.0
182,10316,Jack's New England Clam Chowder,Pescado,7.7,10,Rattlesnake Canyon Grocery,Albuquerque,USA,2014-10-28,77.0
183,10316,Tarte au sucre,Confections,39.4,70,Rattlesnake Canyon Grocery,Albuquerque,USA,2014-10-28,2758.0
184,10317,Chai,Bebidas,14.4,20,Lonesome Pine Restaurant,Portland,USA,2014-10-31,288.0

In [7]:
# Las agrupaciones de un dataframe, como convertirlas a  un dataframe y como guardarlas en un fichero
# Suma del importe por categoria

trimestre2014.groupby(['Category']).Amount.sum() # suma
trimestre2014.groupby(['Category']).Amount.mean() # promedio
trimestre2014.groupby(['Category']).Amount.count() # total

# primero crear un objeto para esta agrupación
amount_category = trimestre2014.groupby(['Category']).Amount.sum()

# vamos a convertir este objeto en un dataframe de pandas
amount_category = pd.DataFrame(amount_category, columns=['Amount'])# con columns indicamos el nombre de la columna, aunque no es necesario
print(amount_category) # es un dataframe sin indice

                 Amount
Category
Bebidas         13606.0
Condiments       6375.6
Confections     17936.3
Dairy Products  16594.0
Grains/Cereals   2275.2
Meat/Poultry    11067.9
Pescado         10353.3
Produce          6141.0

In [49]:
# Al convertir el objeto en un dataframe la columna de Category (izquierda) lo considera un 'indice'
# por lo tanto, lo que tengo que hacer es generar el indice numerico, con reset_index

amount_category = amount_category.reset_index() # coloca los indices para poder trabajar con iloc,por ejemplo
print(amount_category)

         Category   Amount
0       Beverages  13606.0
1      Condiments   6375.6
2     Confections  17936.3
3  Dairy Products  16594.0
4  Grains/Cereals   2275.2
5    Meat/Poultry  11067.9
6         Produce   6141.0
7         Seafood  10353.3

In [ ]:
# Guardar el dataframe en un fichero .csv 
ruta = '/Users/andresrojo/Desktop/Python-PCEP/recursos_dia7/category_group.csv'
# nombre del dataframe + .to_csv(ruta_del archivo, separacion de los valores, si queremos indices )
amount_category.to_csv(ruta, sep= ',' , index = True) 
print("Guardado con éxito")

Guardado con éxito

In [54]:
# Vamos a guardarlo como un .xlsx , como un excel
# nombre de la hora 'sheet_name', el nombre de las columnas, 'header 'y poner el indice con 'index'
ruta2 = '/Users/andresrojo/Desktop/Python-PCEP/recursos_dia7/category_group.xlsx'
amount_category.to_excel(ruta2, sheet_name = 'Categorias', header = True, index = True)
print('Guardado con éxito')

Guardado con éxito

In [11]:
# Como trabajar con 'merge'

# Conectarnos a un excel
ruta3 = '/Users/andresrojo/Desktop/Python-PCEP/recursos_dia7/Practica Merge Pandas.xlsx'
facturas = pd.read_excel(ruta3, sheet_name = 'Facturas') # seleccionamos la hoja en el fichero excel
print(facturas)

clientes =pd.read_excel(ruta3, sheet_name = 'Clientes')
print(clientes)

   IdFactura  IdCliente  Importe
0        101          1      200
1        102          2      450
2        103          3      300
3        104          4      500
   IdCliente                Nombre
0          1  Max Industries S.L.U
1          2          Alfa Systems
2          3  Slot Components S.A.
3          5            Debian DOS

In [ ]:
# hacemos la conbinación o merge, con la función 'merge', necesitamos un objeto nuevo

datos_completos = pd.merge(facturas, clientes, on = 'IdCliente')# los unimos por el campo 'IdCliente'
print(datos_completos) # solo muestra los registros que coinciden con ambos dataframes 
# esto es un INNER JOIN (Intersección, solo muestra los registros coincidentes)
print()
datos_completos = pd.merge(facturas, clientes, on= 'IdCliente', how = 'inner')# inner es el tipo de combinación, es lo mismo que el anterior
print(datos_completos)
print()
# nombres de los campos diferentes
#datos_completos2 = pd.merge(facturas, clientes, left_on = 'IdCliente', 
                            #right_on = 'Cliente', how ='inner')# se une con las columnas de diferente nobre 'client' 'idcliente'
# si nos da error vamos a cambiar el nombre de columnas diferentes
clientes = clientes.rename(columns = {'IdClientes':'Clientes'})
datos_completos2 = pd.merge(facturas, clientes, left_on = 'IdCliente', 
                            right_on = 'Clientes', how ='inner') # da error porque no hemos añadido la columna 'Clientes' manualmente
datos_completos2

   IdFactura  IdCliente  Importe                Nombre
0        101          1      200  Max Industries S.L.U
1        102          2      450          Alfa Systems
2        103          3      300  Slot Components S.A.

   IdFactura  IdCliente  Importe                Nombre
0        101          1      200  Max Industries S.L.U
1        102          2      450          Alfa Systems
2        103          3      300  Slot Components S.A.

KeyError: 'Clientes'

In [ ]:
# Ver todas las facturas, aunque no coincida con clientes, allí donde no hay registro saldrá en blanco o NAN
datos_completos_left = pd.merge(facturas, clientes, on= 'IdCliente', how = 'left')# inner es el tipo de combinación, es lo mismo que el anterior
print(datos_completos_left) # LEFT JOIN
print()

   IdFactura  IdCliente  Importe                Nombre
0        101          1      200  Max Industries S.L.U
1        102          2      450          Alfa Systems
2        103          3      300  Slot Components S.A.
3        104          4      500                   NaN

In [ ]:
# Ver todas las facturas, aunque no coincida con clientes, alli donde no hay registro saldrá en blanco o NAN
datos_completos_right = pd.merge(facturas, clientes, on= 'IdCliente', how = 'right')# inner es el tipo de combinación, es lo mismo que el anterior
print(datos_completos_right) # right JOIN
print()

   IdFactura  IdCliente  Importe                Nombre
0      101.0          1    200.0  Max Industries S.L.U
1      102.0          2    450.0          Alfa Systems
2      103.0          3    300.0  Slot Components S.A.
3        NaN          5      NaN            Debian DOS

In [ ]:
# Ver la combinación completa FULL OUTER JOIN , mantendrá todos los registros, alli donde no hay importe ,nombre y factura, pondrá NAN
datos_completos_outer = pd.merge(facturas, clientes, on= 'IdCliente', how = 'outer')# inner es el tipo de combinación, es lo mismo que el anterior
print(datos_completos_outer) # LEFT outer
print()

   IdFactura  IdCliente  Importe                Nombre
0      101.0          1    200.0  Max Industries S.L.U
1      102.0          2    450.0          Alfa Systems
2      103.0          3    300.0  Slot Components S.A.
3      104.0          4    500.0                   NaN
4        NaN          5      NaN            Debian DOS